car_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('maintenance.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as generic_views
from django.urls import reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', generic_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', generic_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', generic_views.PasswordResetView.as_view(
        template_name='users/password_reset.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password-reset-done')), name='password-reset'),
    path('password-reset/done/', generic_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', generic_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password-reset-complete')), name='password-reset-confirm'),
    path('password-reset-complete/', generic_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password-reset-complete'),
    path('profile/', views.profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    img = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.img.path)
        if img.height > 300 or img.width > 300:
            img.thumbnail((300, 300))
            img.save(self.img.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']
        help_texts = {
            'username': '',
        }


class ProfileUpdateForm(forms.ModelForm):

    img = forms.ImageField(widget=forms.FileInput)

    class Meta:

        model = Profile
        fields = ['img']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Account successfully created for {username}! You may now log in to your account.')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            username = u_form.cleaned_data.get('username')
            messages.success(
                request, f'Account successfully updated for {username}!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Zaloguj się</legend>
            {{ form.as_table }}
        </fieldset>
        <div class="">
            <button class="" type="submit">Zaloguj się</button>
            <small class=""><a href="{% url 'users:password-reset' %}">Zapomniałeś/aś hasła?</a></small>
        </div>
    </form>
    <div class="">
        <small class="">Potrzebujesz konta? <a class="" href="{% url 'users:register' %}">Zarejestruj się</a></small>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">
    <small class=""><a href="{% url 'users:login' %}">Zaloguj się znowu</a></small>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Zresetuj hasło używając swojego maila</legend>
            {{ form.as_table }}
        </fieldset>
        <div class="">
            <button class="" type="submit">Wyślij maila z linkiem do zmiany hasła</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">Twoje hasło zostało zmienione
</div>
<a href="{% url 'users:login' %}">Zaloguj się tutaj</a>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Reset hasła</legend>
            {{ form.as_table }}
        </fieldset>
        <div class="">
            <button class="" type="submit">Zresetuj hasło</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">Email z instrukcjami w celu resetu hasła został wysłany na Twojego maila.
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Otrzymujesz tego maila w celu resetu Twojego hasła na
{{ site_name }}.{% endblocktrans %}

{% trans "Przejdź na poniższą stronę i podaj nowe hasło:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Twoja nazwa użytkownika to:' %} {{ user.get_username }}

{% trans "Dzięki za korzystanie z naszej strony!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

users/templates/users/profile.html
{% extends "base_generic.html" %}

{% block main %}
<div>
    <div class="">
        <img class="img-profile" src="{{ user.profile.img.url }}">
        <div class="">
            <h2 class="">{{ user.username }}</h2>
            <p class="">{{ user.email }}</p>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Profile info</legend>
            <table>
                {{ u_form.as_table }}
                {{ p_form.as_table }}
            </table>
        </fieldset>
        <div class="">
            <button class="" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "base_generic.html" %}

{% block main %}
<div class="">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Rejestracja użytkownika</legend>
            {{ form.as_table }}
        </fieldset>
        <div class="">
            <button class="" type="submit">Zarejestruj się</button>
        </div>
    </form>
    <div class="">
        <small class="">Masz już konto?
            <a class="" href="{% url 'users:login' %}">
                Zaloguj się
            </a>
        </small>
    </div>
</div>
{% endblock %}