car_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('maintenance.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maintenance/urls.py
from django.urls import path
from . import views

app_name = 'maintenance'

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.CarList.as_view(), name='cars'),
    path('car/add', views.CarCreate.as_view(), name='car-create'),
    path('car/<int:pk>', views.CarDetail.as_view(), name='car-detail'),
    path('car/<int:pk>/update', views.CarUpdate.as_view(), name='car-update'),
    path('car/<int:pk>/delete', views.CarDelete.as_view(), name='car-delete'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as generic_views
from django.urls import reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', generic_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', generic_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', generic_views.PasswordResetView.as_view(
        template_name='users/password_reset.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password-reset-done')), name='password-reset'),
    path('password-reset/done/', generic_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', generic_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password-reset-complete')), name='password-reset-confirm'),
    path('password-reset-complete/', generic_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password-reset-complete'),
    path('profile/', views.profile, name='profile'),
]

maintenance/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User


class Car(models.Model):

    INSURANCE_DURATION_CHOICES = [
        ('12', 'rok'),
        ('6', 'pół roku'),
        ('3', 'trzy miesiące'),
        ('1', 'miesiąc'),
    ]

    make = models.CharField(max_length=64, verbose_name='Marka')
    model = models.CharField(max_length=64, verbose_name='Model')
    year = models.DateField(verbose_name='Rok produkcji')
    mileage = models.PositiveIntegerField(verbose_name='Przebieg')
    oil_service_interval = models.PositiveSmallIntegerField(
        verbose_name='Interwał wymiany oleju')
    oil_service_date_last_done = models.DateField(
        verbose_name='Data ostatniej wymiany oleju')
    oil_service_mileage_last_done = models.PositiveIntegerField(
        verbose_name='Przebieg przy ostatniej wymianie oleju')
    oil_service_oil_type = models.CharField(
        max_length=128, verbose_name='Rodzaj oleju')
    last_inspection = models.DateField(
        verbose_name='Data ostatniego przeglądu')
    last_insurance = models.DateField(
        verbose_name='Data zawarcia ostatniej umowy OC')
    insurance_duration = models.CharField(
        max_length=2, choices=INSURANCE_DURATION_CHOICES, verbose_name='Czas trwania umowy OC')
    owner = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name='Właściciel')

    def get_fields_for_detail_template(self):
        """ Gets iterable for the loop in template """
        return [
            (field.verbose_name, self.get_insurance_duration_display() if field.name ==
             'insurance_duration' else field.value_to_string(self))
            for field in Car._meta.fields
            if field.name not in ["owner", "id", "make", "model"]
        ]

    def get_absolute_url(self):
        return reverse("maintenance:car-detail", args=[str(self.id)])

    def __str__(self):
        return f'{self.make} {self.model}'

maintenance/forms.py
from django import forms
from .models import Car


class CarCreateForm(forms.ModelForm):

    class Meta:

        model = Car
        exclude = ('owner',)


class CarUpdateForm(forms.ModelForm):

    class Meta:

        model = Car
        exclude = ('owner',)

maintenance/views.py
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Car
from .forms import (
    CarCreateForm,
    CarUpdateForm,
)


def index(request):
    return render(request, "index.html")


class CarList(LoginRequiredMixin, generic.ListView):

    model = Car
    paginate_by = 10

    def get_queryset(self):
        return Car.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(CarList, self).get_context_data(**kwargs)
        context["title"] = "Lista samochodów"
        return context


class CarDetail(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):

    model = Car

    def test_func(self):
        car = self.get_object()
        return self.request.user == car.owner

    def get_context_data(self, **kwargs):
        context = super(CarDetail, self).get_context_data(**kwargs)
        context["title"] = "Informacje o samochodzie"
        return context


class CarCreate(LoginRequiredMixin, generic.edit.CreateView):

    model = Car
    form_class = CarCreateForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CarCreate, self).get_context_data(**kwargs)
        context["title"] = "Dodaj nowy samochód"
        return context


class CarUpdate(LoginRequiredMixin, UserPassesTestMixin, generic.edit.UpdateView):

    model = Car
    form_class = CarUpdateForm

    def test_func(self):
        car = self.get_object()
        return self.request.user == car.owner

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CarUpdate, self).get_context_data(**kwargs)
        context["title"] = "Zmień dane"
        return context


class CarDelete(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):

    model = Car
    success_url = "/breeding/cars"

    def test_func(self):
        car = self.get_object()
        return self.request.user == car.owner

    def get_context_data(self, **kwargs):
        context = super(CarDelete, self).get_context_data(**kwargs)
        context["title"] = "Usuń samochód"
        return context

maintenance/templates/maintenance/car_confirm_delete.html
{% extends "base_generic.html" %}

{% block main %}
<main>
    <form action="" method="post">
        {% csrf_token %}
        <h4>Czy na pewno chcesz usunąć samochód "{{ car }}"?</h4>
        <button class="" type="submit" value="Submit">Usuń</button>
        <a href="{% url 'maintenance:car-detail' object.id %}" class="">Wróć</a>
    </form>
</main>
{% endblock %}

maintenance/templates/maintenance/car_detail.html
{% extends "base_generic.html" %}

{% block main %}
<main>
    <h3 class="">Szczegóły samochodu:</h3>
    <h1>{{ car }}</h1>
    <dl>
        {% for key, value in car.get_fields_for_detail_template %}
        <dt>{{ key }}</dt>
        <dd>{{ value }}</dd>
        {% endfor %}
    </dl>
    <div>
        <a class="" href="{% url 'maintenance:car-update' object.id %}">Zmień dane</a></br>
        <a class="" href="{% url 'maintenance:car-delete' object.id %}">Usuń samochód</a>
    </div>
</main>
{% endblock %}

maintenance/templates/maintenance/car_form.html
{% extends "base_generic.html" %}

{% block main %}
<main>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button class="" type="submit" value="Submit">Wyślij</button>
    </form>
</main>
{% endblock %}

maintenance/templates/maintenance/car_list.html
{% extends "base_generic.html" %}

{% block main %}
<main>
    {% if object_list %}
    <h3>Wybierz samochód, aby zobaczyć szczegóły</h3>
    <ul>
        {% for car in object_list %}
        <li>
            <a href="{% url 'maintenance:car-detail' car.id %}">{{ car }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nie ma żadnych samochodów. Dodaj nowe za pomocą linku "Dodaj samochód"</p>
    {% endif %}
</main>
{% endblock %}